language: node_js
node_js: 
  - "stable"
  - "10"
  - "9"
  - "8"
cache:
  directories:
    - "node_modules"
script:
  - npm install
  - node index.js host tests/host.test.clio &
  - sleep 10
  - npm test